server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_world
    username: root
    password: chldmsrl12

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
